# Generated by Django 2.1.3 on 2018-11-30 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_serial', models.IntegerField()),
                ('group_name', models.CharField(max_length=40)),
                ('group_register_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_request_or_answer', models.BooleanField()),
                ('message_join_or_quit', models.BooleanField()),
                ('message_revised', models.BooleanField()),
                ('message_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SerailNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_group', models.IntegerField()),
                ('serial_submission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('student_regiter_time', models.DateTimeField()),
                ('student_is_leader', models.BooleanField()),
                ('student_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_serial', models.IntegerField()),
                ('submission_file_h', models.FileField(upload_to='')),
                ('submission_file_cc', models.FileField(upload_to='')),
                ('submission_time', models.DateTimeField()),
                ('submission_revised', models.BooleanField()),
                ('submission_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_subject', models.CharField(max_length=40)),
                ('suggestion_content', models.TextField()),
                ('suggestion_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Student')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Submission'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='lab3app.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='lab3app.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3app.Student'),
        ),
    ]
